# Generated by Django 3.2.9 on 2021-11-17 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=1, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('sn', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('specmain', models.CharField(max_length=100)),
                ('specsub', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('is_inquiry', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='quotation.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('sn', models.CharField(max_length=10, unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=20)),
                ('spnsr', models.CharField(max_length=20)),
                ('spnsr_shrtname', models.CharField(blank=True, max_length=20, null=True)),
                ('tel', models.CharField(max_length=20)),
                ('tel_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('remark', models.CharField(blank=True, max_length=300, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
