# Generated by Django 3.2.9 on 2021-11-17 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=12)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('status', models.CharField(choices=[('詢價中', 'Ongoing'), ('結案', 'End')], default='詢價中', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquirys', to=settings.AUTH_USER_MODEL)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquirys', to='quotation.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquirys', to='quotation.company')),
            ],
        ),
    ]
