# Generated by Django 3.2.9 on 2021-11-17 07:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='inquiry',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='remark',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='updatetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ItemQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('xchgrt', models.DecimalField(decimal_places=6, max_digits=6)),
                ('is_new', models.BooleanField(default=False)),
                ('crnt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemquota', to='quotation.current')),
                ('inquirysn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemquota', to='quotation.inquiry')),
                ('itemsn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemquota', to='quotation.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
