# Generated by Django 3.2.9 on 2021-11-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_auto_20211118_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquota',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
