# Generated by Django 3.2.9 on 2021-11-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_auto_20211123_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemquota',
            name='qdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
