# Generated by Django 3.2.9 on 2021-11-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_itemquota_qdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquota',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
    ]
