# Generated by Django 3.2.9 on 2021-11-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_alter_itemquota_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquota',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='itemquota',
            name='xchgrt',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
