# Generated by Django 3.2.9 on 2021-11-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0009_auto_20211124_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquota',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
