# Generated by Django 3.2.9 on 2021-12-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_historicalcompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCompany',
        ),
    ]
