# Generated by Django 3.2.9 on 2021-12-20 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotation', '0014_historicalcompany_historicalinquiry_historicalitem_historicalitemquota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sn',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='sn',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('is_open', models.BooleanField(default=True)),
                ('sn', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer', to='quotation.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalManufacturer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('addtime', models.DateTimeField(blank=True, editable=False)),
                ('updatetime', models.DateTimeField(blank=True, editable=False)),
                ('is_open', models.BooleanField(default=True)),
                ('sn', models.CharField(db_index=True, max_length=4)),
                ('name', models.CharField(max_length=50)),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quotation.category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical manufacturer',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
