# Generated by Django 3.2.9 on 2021-12-20 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0015_auto_20211220_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='mfg',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quotation.manufacturer'),
        ),
        migrations.AddField(
            model_name='item',
            name='mfg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='quotation.manufacturer'),
            preserve_default=False,
        ),
    ]
