# Generated by Django 3.2.9 on 2021-12-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0016_auto_20211220_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitem',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='specsub',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='item',
            name='specsub',
        ),
    ]
