# Generated by Django 3.2.9 on 2022-01-17 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0018_Add_add_update_isopen_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='cate',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_open': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quotation.category'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='mfg',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_open': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quotation.manufacturer'),
        ),
        migrations.AlterField(
            model_name='historicalmanufacturer',
            name='cate',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_open': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quotation.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cate',
            field=models.ForeignKey(limit_choices_to={'is_open': True}, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='quotation.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mfg',
            field=models.ForeignKey(limit_choices_to={'is_open': True}, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='quotation.manufacturer'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='cate',
            field=models.ForeignKey(limit_choices_to={'is_open': True}, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer', to='quotation.category'),
        ),
    ]
