# Generated by Django 3.2.9 on 2022-01-17 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0019_auto_20220117_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinquiry',
            name='cate',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_open': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quotation.category'),
        ),
        migrations.AlterField(
            model_name='historicalinquiry',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_open': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quotation.company'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='cate',
            field=models.ForeignKey(limit_choices_to={'is_open': True}, on_delete=django.db.models.deletion.PROTECT, related_name='inquirys', to='quotation.category'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='company',
            field=models.ForeignKey(limit_choices_to={'is_open': True}, on_delete=django.db.models.deletion.PROTECT, related_name='inquirys', to='quotation.company'),
        ),
    ]
